Components for serverside data rendering
4teamwork/ui pull request #1
Opened 2021-10-19 09:29 UTC by lvonlanthen

2021-10-19 10:32 UTC, bierik requested changes

2021-10-19 10:32 UTC, bierik commented on lib/components/menus/OrderingMenu.vue
> +        <v-icon color="primary" icon small v-bind="attrs" v-on="on"> mdi-swap-vertical </v-icon>
Ich würde hier aus semantischen Gründen ein `v-btn` drumliire.

2021-10-19 10:32 UTC, bierik commented on lib/components/menus/OrderingMenu.vue
> +            <v-icon v-if="item.value === value">mdi-check</v-icon>
Das if würde ich auf das `v-list-item-icon` machen

2021-10-19 10:32 UTC, bierik commented on lib/components/serverside-data/Table.vue
> +              <svg-icon v-else :name="$attrs.icon" width="18px" height="18px" />
```suggestion
              <v-icon width="18px" height="18px">{{ $attrs.icon }}</v-icon>
```
Ich würde hier nur mal mdi icons anbieten. Wie gesagt schauen wir svg-icons später an.

2021-10-20 10:04 UTC, lvonlanthen commented on lib/components/serverside-data/Table.vue
> +              <svg-icon v-else :name="$attrs.icon" width="18px" height="18px" />
👍🏼  done.

2021-10-20 12:18 UTC, lvonlanthen commented on lib/components/serverside-data/Table.vue
> +    :hide-default-footer="true"
👍🏼

2021-10-20 12:28 UTC, lvonlanthen commented on docs/components/serverside-data/README.md
> +The ``ftw-serverside-collection`` component is used to display data fetched, filtered and sorted by the backend, as returned by the [Django REST Framework](https://www.django-rest-framework.org/).
👍🏼

2021-10-20 13:27 UTC, merged