Render app-switcher apps with url values as anchor elements
4teamwork/ui pull request #21
Opened 2022-08-05 10:33 UTC by blu93

2022-08-05 11:31 UTC, 2e12 approved these changes
LGTM

2022-08-05 12:33 UTC, 2e12 approved these changes

2022-08-05 13:44 UTC, bierik requested changes

2022-08-05 13:44 UTC, bierik commented on lib/components/app-switcher/AppSwitcher.vue
> +            :tag="useAnchorTags && app.url && !app.disabled ? 'a' : 'div'"
Ich habe das kurz getestet. Vuetify macht keinen link wenn `href` leer ist. Wenn also `app.url` nicht gesetzt ist, wird es automatisch ein `div` tag. Ich denke also nicht, dass du das tag manuell setzen musst.

2022-08-05 13:44 UTC, bierik commented on lib/components/app-switcher/AppSwitcher.vue
> +    },
Ich würde das nicht konfigurierbar machen, und immer einen link anzeigen. Oder hast du einen konkreten use-case dafür?

2022-08-08 07:02 UTC, blu93 commented on lib/components/app-switcher/AppSwitcher.vue
> +            :tag="useAnchorTags && app.url && !app.disabled ? 'a' : 'div'"
Nice, hab das geändert dass es einfach nur href setzt

2022-08-08 07:02 UTC, blu93 commented on lib/components/app-switcher/AppSwitcher.vue
> +    },
gone 👌

2022-08-08 07:10 UTC, bierik approved these changes

2022-08-08 07:31 UTC, merged